package main

import (
	_ "goapi/docs" // docs is generated by Swag CLI, you have to import it.
	"net/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Sample api
// @version 1.0
// @description Your API description
// @host localhost:9000
// @BasePath /api/v1

func main() {
	r := gin.Default()

	// Register your routes here
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.GET("/api/v1/names", getNames)

	r.Run(":9000")
}

// @Summary List names
// @Description Get a list of names
// @Tags names
// @Accept  json
// @Produce  json
// @Success 200 {array} string
// @Router /names [get]
// @Security ApiKeyAuth
func getNames(c *gin.Context) {
	names := []string{"Alice", "Bob", "Charlie"}
	c.JSON(http.StatusOK, names)
}
